apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-demo02
  labels:
    app: example-demo02
spec:
  replicas: 0
  selector:
    matchLabels:
      app: example-demo02
  template:
    metadata:
      labels:
        app: example-demo02
    spec:
      containers:
      - name: example-demo02
        image: harbor-a.labaq.life/labaq/example-demo02
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: dev
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

