apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

namePrefix: dev-
nameSuffix: -canary

commonLabels:
  app: nginx
  version: v1
  env: dev

configurations:
  - rollout-transform.yaml

resources:
  - deploy.yaml
  - rollout.yaml
  - svc-stable.yaml
  - svc-preview.yaml
  - ing-stable.yaml
  - ing-preview.yaml

configMapGenerator:
  - name: nginx-html
    files:
    - index.html=html/index.html