apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

nameSuffix: -geba
namePrefix: dev-

commonLabels:
  app: superapi
  version: v1
  env: dev

configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml
 
resources:
  - rollout.yaml
  - svc-active.yaml
  - svc-preview.yaml
 
configMapGenerator:
- name: superapi-config
  literals:
    - WELCOME=Hello from v4!
    - PORT=8080
