apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-demo01
  labels:
    app: example-demo01
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-demo01
      version: v2
  template:
    metadata:
      labels:
        app: example-demo01
        version: v2
    spec:
      containers:
      - name: example-demo01
        image: harbor-a.labaq.life/labaq/example-demo01
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: dev
        - name: SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: example-demo01
              key: service_name
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

