apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-demo01
  labels:
    app: example-demo01
spec:
  replicas: 0
  selector:
    matchLabels:
      app: example-demo01
  template:
    metadata:
      labels:
        app: example-demo01
    spec:
      containers:
      - name: example-demo01
        image: harbor.labaq.life/labaq/example-demo01
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: dev
        - name: SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: example-demo01
              key: service_name
        - name: STABLE_SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: example-demo01
              key: stable_service_name
        - name: CANARY_SERVICE_NAME
          valueFrom:
            configMapKeyRef:
              name: example-demo01
              key: canary_service_name
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
      volumes:
      - name: podinfo
        downwardAPI:
          items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels