apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: example-demo01-vs
spec:
  hosts:
  - example-demo01-stable
  gateways:
  - example-demo-gw
  http:
    - name: primary
      route:
      - destination:
          host: example-demo01-canary
          port:
            number: 8080
        weight: 0
      - destination:
          host: example-demo01-stable
          port:
            number: 8080
        weight: 100

