apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  workloadRef:                                 # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  strategy:
    canary:
      canaryService: nginx-canary-preview  # required
      stableService: nginx-canary  # required
#      trafficRouting:
#        nginx:
#          stableIngress: nginx-active  # required
#          annotationPrefix: customingress.nginx.ingress.kubernetes.io # optional
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause:
          duration: 1h # 1 hour
      - setWeight: 20
      - pause: {} # pause indefinitely