apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-canary
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  workloadRef:                                 # Reference an existing Deployment using workloadRef field
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  strategy:
    canary:
      canaryService: nginx-canary-preview  # required
      stableService: nginx-canary  # required
      canaryMetadata:
        annotations:
          role: canary
        labels:
          role: canary
      trafficRouting:
        nginx:
          stableIngress: nginx-active  # required
          annotationPrefix: customingress.nginx.ingress.kubernetes.io # optional
      maxSurge: 1
      maxUnavailable: 0
      scaleDownDelaySeconds: 10
      steps:
      - setWeight: 25
      - pause:
          duration: 1h # 1 hour
      - setWeight: 65
      - pause: {} # pause indefinitely
