apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

namePrefix: dev-

commonLabels:
  app: nginx
  version: v1
  env: dev

configurations:
  - rollout-transform.yaml
 
resources:
  - deploy.yaml
  - rollout.yaml
  - svc-active.yaml
  - svc-preview.yaml
  - ing-active.yaml
  - ing-preview.yaml